### PR TITLE
Fixes for NixOS and for better handling

### PR DESCRIPTION
**Pull request by kamentomov**

### CODE REVIEW

**Comment by notAperson535** [comment]
merged and closing

**Comment by kamentomov** [comment]
There were conflicts

**Comment by notAperson535** [comment]
@kamentomov I just edited the files manually

**Comment by notAperson535** [comment]
@kamentomov does NixOS use apt install?

**Comment by kamentomov** [comment]
> @kamentomov does NixOS use apt install?

no, it has its own package manager

**Comment by notAperson535** [comment]
@kamentomov  how do you install python, pip, and qemu stuff? I would like to put it into the Readme.

**Comment by kamentomov** [comment]
Generally in NIXOS you install software by declaring it in the configuration.nix file. This is also valid for the case in question. It is not an OS for faint-hearted so IMO people who use it definitelly know how to install software. The only thing I was missing in my configuration.nix was the dmg2img package. But you can also mention the qemu package.

**Comment by notAperson535** [comment]
@kamentomov so how could I put that into the readme?

**Comment by kamentomov** [comment]
@notAperson535 sure

**Comment by notAperson535** [comment]
@kamentomov what do you mean by sure?

**Comment by kamentomov** [comment]
> @kamentomov what do you mean by sure?

@notAperson535 sorry for missunderstanding your question. You can say something like that: To use in NIXOS add qemu and dmg2img in your packages list.

**Comment by notAperson535** [comment]
@kamentomov ok, thanks

**Comment by notAperson535** [comment]
@kamentomov can you change `firmware/OVMF_VARS-1024x768.fd` and `firmware/OVMF_VARS.fd` to be compatible with NixOS, and open up a new pr?

**Pull request closed without merging**
